#!/bin/bash

#	codium.sh
#	Script to wrap the codium execution to firsly build the extensions.json
#	file if hasn't been created yet to allow proper vsode load of .hsm extensions
#
#	Copyright (C) 2023, huronOS Project:
#		<http://huronos.org>
#
#	Licensed under the GNU GPL Version 2
#		<http://www.gnu.org/licenses/gpl-2.0.html>
#
#	Authors:
#		Enya Quetzalli <equetzal@huronos.org>

EXTENSIONS_DIR="/opt/codium/contestant/extensions"
EXTENSIONS_FILE="$EXTENSIONS_DIR/extensions.json"
EXTENSIONS_IDS="$EXTENSIONS_DIR/ids"
OBSOLETE_FILE="$EXTENSIONS_DIR/.obsolete"


## If the extensions directory does not exists, then no vscode extention is loaded
## so pass all the arguments and launch codium
if [ ! -e "$EXTENSIONS_DIR" ]; then
	/usr/share/codium/bin/codium "$@"; exit 0
fi


echo -n "[" > "$EXTENSIONS_FILE"
for file in "$EXTENSIONS_IDS"/*; do
	if [ -f "$file" ]; then
		echo -n "$(cat $file)" | tr -d '\n' >> "$EXTENSIONS_FILE"
		echo -n "," >> "$EXTENSIONS_FILE"
	fi
done
sed -i '$ s/,$//' "$EXTENSIONS_FILE"
echo "]" >> "$EXTENSIONS_FILE"
rm -rf "$OBSOLETE_FILE"	## TODO: Find how to update extensions IDs after update for not needing to remove obsoletes


## Call codium with the same arguments it was called but with extensions-dir when not specified
if echo "$@" | grep -qe "--extensions-dir"; then
	/usr/share/codium/bin/codium "$@"
else
	/usr/share/codium/bin/codium --extensions-dir /opt/codium/contestant/extensions/ "$@"
fi