#!/bin/bash

## Define config variables for huronOS
export PATH=.:./tools:../tools:/usr/sbin:/usr/bin:/sbin:/bin:/
export LIVEKITNAME="huronOS"
export BUILD_YEAR="2023"
export BUILD_VERSION="0025"
export VMLINUZ=/boot/vmlinuz-6.0.15-huronos+
export KERNEL="6.0.15-huronos+"
export MKMOD="bin etc home lib lib64 opt root sbin srv usr var"
export NETWORK=false
export HBT_LAB="/tmp/huronOS-build-lab-$$"
export ISO_DATA="$HBT_LAB/iso-data"
export BEXT=hsl
export LMK="lib/modules/$KERNEL"
export DEVELOPER=true