#!/bin/bash

#	Copyright (C) 2022, huronOS Project:
#		<http://huronos.org>
#
#	Licensed under the GNU GPL Version 2
#		<http://www.gnu.org/licenses/gpl-2.0.html>	
#
#	Taken from the Slax project, authored by:
#		Tomas M <http://www.slax.org/>

set -e

if [ "$1" = "-h" -o "$1" = "--help" -o "$2" = "" ]; then
   echo ""
   echo "Unpack initramfs image to a directory"
   echo "Usage: $0 [source_initramfs_file.img] [target_directory]"
   echo ""
   exit 2
fi

mkdir -p "$2"

(cd "$2"; xz -d | cpio -idv) < "$1"
