#!/bin/bash

. /usr/lib/hos/enviroment.sh
. /usr/lib/hos/utils.sh

help(){
	echo "TODO: Write help"
}

main(){
	check_wallpapers "$(hos-dmode)"

}

# $1 = Wallpaper Section
# $2 = Current Mode
prepare_wallpaper(){
	local SECTION CURRENT_MODE WALLPAPER_URL WALLPAPER_HASH_URL FILE_TYPE SAVE_FILE CURRENT_WALLPAPER
	SECTION="$1"
	CURRENT_MODE="$2"
	WALLPAPER_URL="$(hos-dvar --variable-name Wallpaper --section "$SECTION")"
	WALLPAPER_HASH_URL="${WALLPAPER_URL}.sha256"
	BASENAME="$(basename "$WALLPAPER_URL")"
	FILE_TYPE="${BASENAME##*.}"
	SAVE_FILE="$SYSTEM_BACKUP_FILES_DIR/${SECTION}-mode-wallpaper.${FILE_TYPE}"

	## If no URL setup or default is selected, use default wallpaper
	if [ -z "$WALLPAPER_URL" ] || [ "$WALLPAPER_URL" = "default" ]; then
		BASENAME="$(basename "$DEFAULT_WALLPAPER_FILE")"
		FILE_TYPE="${BASENAME##*.}"
		SAVE_FILE="$SYSTEM_BACKUP_FILES_DIR/${SECTION}-mode-wallpaper.${FILE_TYPE}"
		cp -f "$DEFAULT_WALLPAPER_FILE" "$SAVE_FILE"
	## If current file is not valid
	elif should_redownload_file "$SAVE_FILE" "$WALLPAPER_HASH_URL"; then
		## Download the file
		if ! safe_download "$WALLPAPER_URL" "$SAVE_FILE" "$WALLPAPER_HASH_URL"; then
			## If not successfull, leave the file as it is unless there is no file
			if [ ! -f "$SAVE_FILE" ]; then
				## Set default wallpaper
				BASENAME="$(basename "$DEFAULT_WALLPAPER_FILE")"
				FILE_TYPE="${BASENAME##*.}"
				SAVE_FILE="$SYSTEM_BACKUP_FILES_DIR/${SECTION}-mode-wallpaper.${FILE_TYPE}"
				cp -f "$DEFAULT_WALLPAPER_FILE" "$SAVE_FILE"
			fi
		fi
	fi

	if [ "$SECTION" = "$CURRENT_MODE" ]; then
		## Set the wallpaper as current
		CURRENT_WALLPAPER="$CURRENT_WALLPAPERS_DIR/$$-current-wallpaper.${FILE_TYPE}"
		cp -f "$SAVE_FILE" "$CURRENT_WALLPAPER"
		chmod 777 "$CURRENT_WALLPAPER"
		su contestant -c "export DISPLAY=:0; gsettings set org.gnome.desktop.background picture-uri file://$CURRENT_WALLPAPER"
		## Delete previous wallpapers
		find "$CURRENT_WALLPAPERS_DIR/" | grep "current-wallpaper" | grep -v $$ | xargs -n 1 rm -f
	fi

}

# $1 = Current Mode
check_wallpapers(){
	local CURRENT_MODE
	CURRENT_MODE="$1"

	## Check for Always mode
	prepare_wallpaper "Always" "$CURRENT_MODE"

	## Check for Event mode
	prepare_wallpaper "Event" "$CURRENT_MODE"

	## Check for Contest mode
	prepare_wallpaper "Contest" "$CURRENT_MODE"
}

main "$@"; exit 0;
