#!/bin/bash

TMP=/tmp/changes$$
EXCLUDE="^\$|/\$|[.]wh[.][.]wh[.]orph/|^[.]wh[.][.]pwd[.]lock|^[.]wh[.][.]wh[.]plnk/|^[.]wh[.][.]wh[.]aufs|^var/cache/|^var/log/hsync.log|^var/log/journal|^run/log/journal|^var/backups/|^var/tmp/|^var/log/|^var/lib/apt/|^var/lib/dhcp/|^var/lib/systemd/|^sbin/fsck[.]aufs|^etc/resolv[.]conf|^home/contestant/[.]bash_history|^home/contestant/[.]Xauthority|^home/contestant/[.]xsession-errors|^home/contestant/[.]fehbg|^root/[.]bash_history|^root/[.]Xauthority|^root/[.]xsession-errors|^root/[.]fehbg|^root/|^etc/timezone|^etc/localtime|^etc/hsync/|^etc/hmm/|^etc/mtab|^etc/fstab|^usr/share/backgrounds/custom-|^boot/|^dev/|^mnt/|^proc/|^run/|^sys/|^tmp/"
CHANGES=/run/initramfs/memory/syschanges

if [ "$1" = "" ]; then
   echo ""
   echo "savechanges - save all changed files in a compressed filesystem bundle"
   echo "            - excluding some predefined files such as /etc/mtab,"
   echo "              temp & log files, empty directories, apt cache, and such"
   echo ""
   echo "Usage:"
   echo "        $0 [ target_file.hsm ] [ changes_directory ]"
   echo ""
   echo "If changes_directory is not specified, /run/initramfs/memory/syschanges is used."
   echo ""
   exit 1
fi

if [ ! "$2" = "" ]; then
   CHANGES="$2"
fi

# Overlayfs requires one more subdir. Detect it this way
if [ -d "$CHANGES/changes" -a -d "$CHANGES/workdir" -a "$(ls -1 "$CHANGES" | egrep -v '^changes$' | egrep -v '^workdir')" = "" ]; then
   CHANGES="$CHANGES/changes"
fi

# exclude control files for automounted disk drives
EXCLUDEDISKS=$(grep "hmount-rule:do_not_save_on_persistence" /etc/systemd/system/{*,*/*} 2>/dev/null | cut -d : -f 1 | cut -b 2- | tr '\n' '|')
if [ "$EXCLUDEDISKS" != "" ]; then
   EXCLUDE="$EXCLUDE|^($EXCLUDEDISKS)\$"
fi

# exclude the save_file itself of course
EXCLUDE="$EXCLUDE|^""$(readlink -f "$1" | cut -b 2- | sed -r "s/[.]/[.]/")""\$"

CWD=$(pwd)

cd $CHANGES || exit

mkdir -p $TMP
mount -t tmpfs tmpfs $TMP

find \( -type d -printf "%p/\n" , -not -type d -print \) \
  | sed -r "s/^[.]\\///" | egrep -v "$EXCLUDE" \
  | while read FILE; do
    cp --parents -afr "$FILE" "$TMP"
    echo "Saving $FILE"
done

cd $CWD

mksquashfs $TMP "$1" -comp xz -b 1024K -always-use-fragments -noappend

umount $TMP
rmdir $TMP
