#!/bin/sh

# Initial script for huronOS
# Taken from Slax, Originally authored by: Tomas M <http://www.slax.org/>
# Modified by the huronOS team:
#	Enya Quetzalli <equetzal@huronos.org>

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

. /lib/config
. /lib/livekitlib

if [ ! -r /lib/initramfs_escaped ]; then
	echo "Starting huronOS"
fi

transfer_initramfs

MEMORY=/memory
CHANGES=$MEMORY/changes
UNION=$MEMORY/union
DATAMNT=$MEMORY/data
BUNDLES=$MEMORY/bundles

header "huronOS Init process <https://huronos.org/>"

echo "Creating target filesystem"
init_proc_sysfs

debug_start
                                                                                                                                                       debug_shell
# load some modules manually first, then modprobe everything we have
init_devs
init_aufs
init_zram

# modprobe all devices excluding network drivers
modprobe_everything -v /drivers/net/

# find data dir with filesystem bundles
DATA="$(find_data 45 "$DATAMNT")"
check_data_found "$DATA"
                                                                                                                                                      debug_shell
# setup persistent changes, if possible
persistent_changes "$DATA" "$CHANGES"
                                                                                                                                                      debug_shell
# copy to RAM if needed
DATA="$(copy_to_ram "$DATA" "$CHANGES")"

# mount bundles
mount_bundles "$DATA" "$BUNDLES"
                                                                                                                                                      debug_shell
# init aufs union, or setup overlayfs union
init_union "$CHANGES" "$UNION" "$BUNDLES"

# add data to aufs union
union_append_bundles "$BUNDLES" "$UNION"
                                                                                                                                                      debug_shell
# rootcopy
copy_rootcopy_content "$DATA" "$UNION"

# create fstab
fstab_create "$UNION" "$DATAMNT"
                                                                                                                                                      debug_shell
# run user custom preinit
# user_preinit "$DATA" "$UNION"

header "huronOS ready!, starting contest enviroment"
header "Keep Training!"
change_root "$UNION"

header "!!ERROR occured, you shouldn't be here.!!"
/bin/sh
